# Convalution examples

In [5]:
import numpy as np 

array = np.array([1.0, 2.0, 3.0])
print(array)

filter_1 = 2


[1. 2. 3.]


Let's try to see the convolution in 1D a with a scalar. The scalar need to translate on each element of the array.

In [6]:
output = np.array([filter_1 * element for element in array])
print(output)

[2. 4. 6.]


Let's now see the convolution made between two array.

In [ ]:
import numpy as np

array = np.array([1., 2., 3., 4., 5.])
filter_1 = np.array([2., 6., 8.])

# Draw for this result array.shape[0] - filter_1.shape[0] + 1) and find the pattern

output = np.array([array[i:i+filter_1.shape[0]] for i in range(array.shape[0] - filter_1.shape[0] + 1)])

output = np.sum(output * filter_1, axis = 1)
print(output)

[38. 54. 70.]


In [ ]:
import numpy as np

array = np.array([1., 2., 3., 4., 5.])
filter_1 = np.array([2., 6., 8.])

output = np.zeros(array.shape[0] - filter_1.shape[0] + 1)
for i in range(len(output)):
    region = array[i:i+len(filter_1)]
    output[i] = np.sum(region * filter_1)

print(output)  # [38. 54. 70.]


[38. 54. 70.]


let's see between an array and a matrix 

In [ ]:
import numpy as np 

array = np.array([[1., 2., 3., 4., 5.],[6. ,7., 8., 9., 10.]]) # to keep the element wise operation
print(array.shape)
filter_1 = np.array([2., 6., 8.])
print(filter_1.shape)
output_shape = (array.shape[0], array.shape[1] - filter_1.shape[0] + 1)
output = np.zeros(output_shape)

for i in range(array.shape[0]):
    for j in range(array.shape[1] - filter_1.shape[0] + 1 ):
        region = array[i, j:j + filter_1.shape[0]]
        output[i,j] = np.sum(region * filter_1)
print(output)


(2, 5)
(3,)
[1. 2. 3.]
[2. 3. 4.]
[3. 4. 5.]
[6. 7. 8.]
[7. 8. 9.]
[ 8.  9. 10.]
[[ 38.  54.  70.]
 [118. 134. 150.]]


let's see between an two matrixs

In [32]:
import numpy as np 

array = np.array([[1., 2., 3., 4., 5.],[6. ,7., 8., 9., 10.]]) # to keep the element wise operation
print(array.shape)
filter_1 = np.array([[2., 6., 8.],[2., 6., 8.]])
print(filter_1.shape)
output_shape = (array.shape[0] - filter_1.shape[0] + 1, array.shape[1] - filter_1.shape[1] + 1)
output = np.zeros(output_shape)

for i in range(array.shape[0] - filter_1.shape[0] + 1): # On rows
    for j in range(array.shape[1] - filter_1.shape[1] + 1 ): # On columns
        region = array[i:i+ filter_1.shape[0], j:j + filter_1.shape[1]]
        output[i,j] = np.sum(region * filter_1)
print(output)

(2, 5)
(2, 3)
[[156. 188. 220.]]
